### ISSUE TITLE
cmd-files

### ISSUE THREAD

**Issue by AonoZan** [AonoZan/Week003Zadatak03#4]
Jasmine de nam napravi par "cmd" fajlova, koji koriste one tekstualne fajlove iz "files" foldera, da možemo testirati program.
Neka budu u folderu "/test".

**Comment by Jaskio** [comment]
mozes testirati i preko eclipse:
Run -> Run Configurations -> Arguments -> i upises ime fajla sa ekstenzijom

**Comment by AonoZan** [comment]
Aha super!
